import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:telnor/authentication/bloc/authentication_bloc.dart';
import 'package:telnor/authentication/bloc/authentication_event.dart';
import 'package:telnor/config/configuration_bloc.dart';
import 'package:telnor/config/configuration_event.dart';
import 'package:telnor/constants/preferences.dart';
import 'package:telnor/login/bloc/login_bloc.dart';
import 'package:telnor/login/bloc/login_event.dart';
import 'package:telnor/login/bloc/login_settings_bloc.dart';
import 'package:telnor/login/bloc/login_settings_event.dart';
import 'package:telnor/login/bloc/login_settings_state.dart';
import 'package:telnor/login/bloc/login_state.dart';
import 'package:telnor/login/bloc/signup_bloc.dart';
import 'package:telnor/login/bloc/signup_state.dart';
import 'package:telnor/login/bloc/signup_event.dart' as signup;
import 'package:telnor/model/configuration.dart';
import 'package:telnor/util/biometrics.dart';
import 'package:telnor/util/extensions.dart';
import 'package:telnor/util/settings.dart';
import 'package:telnor/util/strings.dart';
import 'package:telnor/web/web.dart';
import 'package:telnor/widget/custom_widgets.dart';

part 'presentation/login_screen.dart';
part 'presentation/forgot_password_screen.dart';
part 'presentation/login_settings_screen.dart';
part 'presentation/signup_screen.dart';

part 'widgets/login_form.dart';
