import 'dart:async';
import 'dart:io';

import 'package:auto_hyphenating_text/auto_hyphenating_text.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_autofill_service/flutter_autofill_service.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_pdfview/flutter_pdfview.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:telnor/authentication/bloc/authentication_bloc.dart';
import 'package:telnor/authentication/bloc/authentication_event.dart';
import 'package:telnor/authentication/bloc/authentication_state.dart';
import 'package:telnor/config/configuration_bloc.dart';
import 'package:telnor/constants/colors.dart';
import 'package:telnor/constants/global_variables.dart';
import 'package:telnor/constants/preferences.dart';
import 'package:telnor/model/attachment.dart';
import 'package:telnor/model/filter.dart';
import 'package:telnor/model/location.dart';
import 'package:telnor/model/password.dart';
import 'package:telnor/model/pcrypt_key.dart';
import 'package:telnor/model/team.dart';
import 'package:telnor/passwords/bloc/file_viewer.dart' as f_viewer;
import 'package:telnor/passwords/bloc/password_edit.dart' as p_word_edit;
import 'package:telnor/passwords/bloc/passwords.dart' as p_word;
import 'package:telnor/sharing/index.dart';
import 'package:telnor/util/formatters.dart';
import 'package:telnor/util/location_service.dart';
import 'package:telnor/web/server_adapter.dart';
import 'package:url_launcher/url_launcher.dart' as http;
import 'package:telnor/passwords/presentation/widgets/address_drawer.dart';
import 'package:telnor/passwords/presentation/widgets/location_drawer.dart';
import 'package:telnor/passwords/presentation/widgets/password_edit_body.dart';
import 'package:telnor/passwords/presentation/widgets/passwords_app_bar.dart';
import 'package:telnor/passwords/presentation/widgets/passwords_list.dart';
import 'package:telnor/passwords/presentation/widgets/tags_drawer.dart';
import 'package:telnor/util/settings.dart';
import 'package:telnor/util/strings.dart';
import 'package:telnor/widget/custom_widgets.dart';
import 'package:webview_flutter/webview_flutter.dart';

part 'presentation/screens/passwords_screen.dart';
part 'presentation/screens/password_edit_screen.dart';
part 'presentation/screens/password_details_screen.dart';
part 'presentation/screens/location_viewer_screen.dart';
part 'presentation/screens/file_viewer_screen.dart';
