import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:telnor/authentication/bloc/authentication_bloc.dart' as auth;
import 'package:telnor/authentication/bloc/authentication_bloc.dart';
import 'package:telnor/authentication/bloc/authentication_event.dart';
import 'package:telnor/authentication/bloc/authentication_state.dart' as auth;
import 'package:telnor/authentication/bloc/authentication_state.dart';
import 'package:telnor/config/configuration_bloc.dart';
import 'package:telnor/config/configuration_state.dart';
import 'package:telnor/constants/assets.dart';
import 'package:telnor/constants/colors.dart';
import 'package:telnor/constants/global_variables.dart';
import 'package:telnor/constants/preferences.dart';
import 'package:telnor/home/bloc/tab_bloc.dart';
import 'package:telnor/home/bloc/tab_event.dart';
import 'package:telnor/home/bloc/tab_state.dart';
import 'package:telnor/messages/bloc/messages_bloc.dart';
import 'package:telnor/messages/bloc/messages_event.dart' hide RetryPressed;
import 'package:telnor/messages/bloc/messages_state.dart';
import 'package:telnor/messages/index.dart';
import 'package:telnor/messages/presentation/widgets/messages_app_bar.dart';
import 'package:telnor/model/language.dart';
import 'package:telnor/model/password.dart';
import 'package:telnor/model/user.dart';
import 'package:telnor/notifications/bloc/notifications_bloc.dart';
import 'package:telnor/notifications/bloc/notifications_event.dart'
    hide RetryPressed;
import 'package:telnor/notifications/bloc/notifications_state.dart';
import 'package:telnor/notifications/index.dart';
import 'package:telnor/passwords/bloc/passwords_bloc.dart';
import 'package:telnor/passwords/bloc/passwords_event.dart';
import 'package:telnor/passwords/bloc/passwords_state.dart';
import 'package:telnor/passwords/index.dart';
import 'package:telnor/passwords/presentation/widgets/passwords_app_bar.dart';
import 'package:telnor/passwords/presentation/widgets/passwords_share_info.dart';
import 'package:telnor/settings/bloc/settings_bloc.dart';
import 'package:telnor/settings/index.dart';
import 'package:telnor/sharing/index.dart';
import 'package:telnor/tags/index.dart';
import 'package:telnor/user_info/index.dart';
import 'package:telnor/util/localization.dart';
import 'package:telnor/util/strings.dart';
import 'package:telnor/widget/custom_widgets.dart';
import 'package:url_launcher/url_launcher.dart';

import '../authentication/bloc/authentication_event.dart' as auth;

part 'presentation/screens/home_screen.dart';
part 'presentation/screens/guide_screen.dart';
part 'presentation/screens/splash_screen.dart';
part 'presentation/screens/upgrade_screen.dart';

part 'presentation/widgets/application_drawer.dart';
part 'presentation/widgets/badge_indicator.dart';
part 'presentation/widgets/home_tab_selector.dart';
part 'presentation/widgets/notifying_page_view.dart';
part 'presentation/widgets/page_indicator.dart';
part 'presentation/widgets/user_account_drawer_header.dart';
